version: '3.8'
services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend
    env_file:
      - ../.env
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsimpact
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  pgdata:
